project_name: amass

env:
  - GO111MODULE=on

before:
  hooks:
  - go mod download

builds:
  -
    main: ./cmd/amass/
    binary: amass
    goos:
      - windows
      - linux
      - darwin
      - freebsd
    goarch:
      - amd64
      - 386
      - arm
      - arm64
    env:
      - CGO_ENABLED=0
    ignore:
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: windows
        goarch: 386
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: freebsd
        goarch: arm

archives:
  -
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    replacements:
      darwin: macos
      386: i386
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE
      - README.md
      - doc/*
      - examples/**/*

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

changelog:
  sort: desc
  filters:
    exclude:
    - '^MERGE'
    - "{{ .Tag }}"

release:
  github:
    owner: OWASP
    name: Amass

dockers:
  -
    dockerfile: Dockerfile
    image_templates:
      - "caffix/amass:v{{ .Major }}"
      - "caffix/amass:v{{ .Major }}.{{ .Minor }}"
      - "caffix/amass:{{ .Tag }}"
      - "caffix/amass:latest"

brews:
  -
    name: amass
    tap:
      owner: caffix
      name: homebrew-amass
    url_template: "https://github.com/OWASP/Amass/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: caffix
      email: caffix@users.noreply.github.com
    folder: Formula
    homepage: "https://owasp.org/www-project-amass/"
    description: "In-depth Attack Surface Mapping and Asset Discovery"
    test: |
      system "#{bin}/amass --version"
    install: |
      bin.install "amass"

snapcrafts:
  -
    name: amass
    # Remember you need to `snapcraft login` first.
    publish: true
    summary: In-depth Attack Surface Mapping and Asset Discovery.
    description: The OWASP Amass Project has developed a tool to help information security professionals perform network mapping of attack surfaces and external asset discovery using open source information gathering and active reconnaissance techniques.
    grade: stable
    confinement: strict
    # Your app's license, based on SPDX license expressions: https://spdx.org/licenses
    license: Apache-2.0	

    apps:
      amass:
        plugs: ["home", "network", "removable-media", "dot-amass"]

    plugs:
      dot-amass:
        interface: personal-files
        write:
        - $HOME/.amass
        - $HOME/.config/amass
